import "./App.css";
import SidebarComponent from "./components/sidebar/SidebarComponent";
import MainAreaComponent from "./components/mainArea/MainAreaComponent";
import ChatComponent from "./components/chatWithAI/ChatComponent";


function App() {
  console.log("Hey Dev! This is a demo of an AI-powered spreadsheet analysis tool. Upload an Excel file to see insights generated by AI. Built with React, TypeScript, and a custom AI backend. Feel free to explore the code and test it with your own spreadsheets!");


  return (
    <div className="container">
      <SidebarComponent/>
      <MainAreaComponent/>
      <ChatComponent />
    </div>
  );
};

export default App;


